@Codebreaker.GameAPIs_HostAddress = http://localhost:9400
@ContentType = application/json

### Create a game
POST {{Codebreaker.GameAPIs_HostAddress}}/games/
Content-Type: {{ContentType}}

{
  "gameType": "Game6x4",
  "playerName": "test"
}

### Set a move

@id = 90ae68d4-221b-4dbb-838c-beb3472e8f4c

PATCH {{Codebreaker.GameAPIs_HostAddress}}/games/{{id}}
Content-Type: {{ContentType}}

{
  "gameType": "Game6x4",
  "playerName": "test",
  "moveNumber": 1,
  "guessPegs": [
    "Red",
    "Green",
    "Blue",
    "Yellow"
  ]
}

### Create a 8x5 game
POST {{Codebreaker.GameAPIs_HostAddress}}/games/
Content-Type: {{ContentType}}

{
  "gameType": "Game8x5",
  "playerName": "test"
}

### Set a 8x5 move

PATCH {{Codebreaker.GameAPIs_HostAddress}}/games/{{id}}
Content-Type: {{ContentType}}

{
  "gameType": "Game8x5",
  "playerName": "test",
  "moveNumber": 1,
  "guessPegs": [
    "Green",
    "Green",
    "Yellow",
    "Purple",
    "Pink"
  ]
}

### Create a 5x5x4 game
POST {{Codebreaker.GameAPIs_HostAddress}}/games/
Content-Type: {{ContentType}}

{
  "gameType": "Game5x5x4",
  "playerName": "test"
}

### Set a 5x5x4 move

PATCH {{Codebreaker.GameAPIs_HostAddress}}/games/{{id}}
Content-Type: {{ContentType}}

{
  "gameType": "Game5x5x4",
  "playerName": "test",
  "moveNumber": 1,
  "guessPegs": [
    "Square;Red",
    "Rectangle;Red",
    "Circle;Green",
    "Rectangle;Purple"
  ]
}



### Get game information

GET {{Codebreaker.GameAPIs_HostAddress}}/games/{{id}}

### Get games by date

GET {{Codebreaker.GameAPIs_HostAddress}}/games/?date=2024-07-14

### Get games by player

GET {{Codebreaker.GameAPIs_HostAddress}}/games/?playerName=test&ended=false

### Get games by date and player

GET {{Codebreaker.GameAPIs_HostAddress}}/games/?date=2024-07-14&playerName=test

### Get games by player

GET {{Codebreaker.GameAPIs_HostAddress}}/games/?playerName=test

### Stop a game

PATCH {{Codebreaker.GameAPIs_HostAddress}}/games/{{id}}
Content-Type: {{ContentType}}

{
  "gameType": "Game6x4",
  "playerName": "test",
  "moveNumber": 1,
  "end": true
}