@Codebreaker.GameAPIs_HostAddress = http://localhost:9400
@ContentType = application/json

### Create a game
POST {{Codebreaker.GameAPIs_HostAddress}}/games/
Content-Type: {{ContentType}}

{
  "gameType": "Game6x4",
  "playerName": "test"
}

### Create a 8x5 game
POST {{Codebreaker.GameAPIs_HostAddress}}/games/
Content-Type: {{ContentType}}

{
  "gameType": "Game8x5",
  "playerName": "test"
}

### Create a 5x5x4 game
POST {{Codebreaker.GameAPIs_HostAddress}}/games/
Content-Type: {{ContentType}}

{
  "gameType": "Game5x5x4",
  "playerName": "test"
}

### Set a move

@gameid = 704602fe-8caf-4821-9a6b-d6fb3ced6b44

PATCH {{Codebreaker.GameAPIs_HostAddress}}/games/{{gameid}}/moves
Content-Type: {{ContentType}}

{
  "gameType": "Game6x4",
  "playerName": "test",
  "moveNumber": 1,
  "guessPegs": [
    "Red",
    "Green",
    "Blue",
    "Yellow"
  ]
}

### Get game information

GET {{Codebreaker.GameAPIs_HostAddress}}/games/{{gameid}}

### Get games per game type

GET {{Codebreaker.GameAPIs_HostAddress}}/games/?gameType=Game6x4 

### Get games per player name

GET {{Codebreaker.GameAPIs_HostAddress}}/games/?playerName=test 


### Get games per day and game type

GET {{Codebreaker.GameAPIs_HostAddress}}/games/?gameType=Game6x4&date=2023-07-09