@Codebreaker.GameAPIs_HostAddress = http://localhost:9400
@ContentType = application/json

### Create a game
POST {{Codebreaker.GameAPIs_HostAddress}}/games/
Content-Type: {{ContentType}}

{
  "gameType": "Game6x4",
  "playerName": "test"
}

### Set a move

@gameid = 9a154941-65b7-4655-9b24-0f4a03ac40ac

PATCH {{Codebreaker.GameAPIs_HostAddress}}/games/{{gameid}}/moves
Content-Type: {{ContentType}}

{
  "gameType": "Game6x4",
  "playerName": "test",
  "moveNumber": 4,
  "guessPegs": [
    "Red",
    "Green",
    "Blue",
    "Yellow"
  ]
}

### Get game information

GET {{Codebreaker.GameAPIs_HostAddress}}/games/{{gameid}}
