// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Codebreaker.Client.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.16.0")]
    #pragma warning disable CS1591
    public enum GameType
    #pragma warning restore CS1591
    {
        [EnumMember(Value = "Game6x4")]
        #pragma warning disable CS1591
        Game6x4,
        #pragma warning restore CS1591
        [EnumMember(Value = "Game6x4Mini")]
        #pragma warning disable CS1591
        Game6x4Mini,
        #pragma warning restore CS1591
        [EnumMember(Value = "Game8x5")]
        #pragma warning disable CS1591
        Game8x5,
        #pragma warning restore CS1591
        [EnumMember(Value = "Game5x5x4")]
        #pragma warning disable CS1591
        Game5x5x4,
        #pragma warning restore CS1591
    }
}
