//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CodeBreaker.Blazor.Client.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CodeBreaker.Blazor.Client.Resources.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current language.
        /// </summary>
        public static string About_Information_Language {
            get {
                return ResourceManager.GetString("About_Information_Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Information.
        /// </summary>
        public static string About_Information_Tab {
            get {
                return ResourceManager.GetString("About_Information_Tab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to App Theme.
        /// </summary>
        public static string About_Information_Theme {
            get {
                return ResourceManager.GetString("About_Information_Theme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Version.
        /// </summary>
        public static string About_Information_Version {
            get {
                return ResourceManager.GetString("About_Information_Version", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;p&gt;The game is played using:&lt;/p&gt;
        ///        &lt;ul&gt;
        ///            &lt;li&gt;
        ///                a decoding board, with a shield at one end covering a row of four large holes, and twelve (or ten, or eight, or six) additional rows containing four large holes next to a set of four small holes;
        ///            &lt;/li&gt;
        ///            &lt;li&gt;
        ///                code pegs of six different colors (or more; see Variations below), with round heads, which will be placed in the large holes on the board; and
        ///            &lt;/li&gt;
        ///            &lt;li&gt;        /// [rest of string was truncated]&quot;;.
        /// </summary>
        public static string About_Instructions {
            get {
                return ResourceManager.GetString("About_Instructions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Instructions.
        /// </summary>
        public static string About_Instructions_Tab {
            get {
                return ResourceManager.GetString("About_Instructions_Tab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No version found..
        /// </summary>
        public static string About_NoVersion_Found {
            get {
                return ResourceManager.GetString("About_NoVersion_Found", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        public static string About_Title {
            get {
                return ResourceManager.GetString("About_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CodeBreaker.
        /// </summary>
        public static string AppDescription {
            get {
                return ResourceManager.GetString("AppDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CodeBreaker.
        /// </summary>
        public static string AppDisplayName {
            get {
                return ResourceManager.GetString("AppDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Continue as Guest.
        /// </summary>
        public static string AuthPage_ContinueAsGuest {
            get {
                return ResourceManager.GetString("AuthPage_ContinueAsGuest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can play games, but you won&apos;t get listed in the scoreboard..
        /// </summary>
        public static string AuthPage_GuestTooltip {
            get {
                return ResourceManager.GetString("AuthPage_GuestTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to or.
        /// </summary>
        public static string AuthPage_Or {
            get {
                return ResourceManager.GetString("AuthPage_Or", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign in.
        /// </summary>
        public static string AuthPage_SignIn {
            get {
                return ResourceManager.GetString("AuthPage_SignIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to sign up.
        /// </summary>
        public static string AuthPage_SignUp {
            get {
                return ResourceManager.GetString("AuthPage_SignUp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome to.
        /// </summary>
        public static string AuthPage_WelcomeTo {
            get {
                return ResourceManager.GetString("AuthPage_WelcomeTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string GamePage_CancelButtonText {
            get {
                return ResourceManager.GetString("GamePage_CancelButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you really want to cancel the game?.
        /// </summary>
        public static string GamePage_CancelConfirmContent {
            get {
                return ResourceManager.GetString("GamePage_CancelConfirmContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel game.
        /// </summary>
        public static string GamePage_CancelConfirmTitle {
            get {
                return ResourceManager.GetString("GamePage_CancelConfirmTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you really want to stop this game?.
        /// </summary>
        public static string GamePage_CancelGame_Info {
            get {
                return ResourceManager.GetString("GamePage_CancelGame_Info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You lose this game..
        /// </summary>
        public static string GamePage_FinishGame_Lose {
            get {
                return ResourceManager.GetString("GamePage_FinishGame_Lose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        public static string GamePage_FinishGame_Ok {
            get {
                return ResourceManager.GetString("GamePage_FinishGame_Ok", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start new game.
        /// </summary>
        public static string GamePage_FinishGame_Restart {
            get {
                return ResourceManager.GetString("GamePage_FinishGame_Restart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You win this game!.
        /// </summary>
        public static string GamePage_FinishGame_Win {
            get {
                return ResourceManager.GetString("GamePage_FinishGame_Win", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The gamername was already defined during sign-up.
        /// </summary>
        public static string GamePage_NameAlreadyProvidedTooltip {
            get {
                return ResourceManager.GetString("GamePage_NameAlreadyProvidedTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gamername.
        /// </summary>
        public static string GamePage_NameInput {
            get {
                return ResourceManager.GetString("GamePage_NameInput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter your gamername.
        /// </summary>
        public static string GamePage_NameInputPlaceholder {
            get {
                return ResourceManager.GetString("GamePage_NameInputPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start game.
        /// </summary>
        public static string GamePage_StartButtonText {
            get {
                return ResourceManager.GetString("GamePage_StartButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Read More.
        /// </summary>
        public static string Index_Card_About_Action {
            get {
                return ResourceManager.GetString("Index_Card_About_Action", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Need more information about the game? This page is the right one for you..
        /// </summary>
        public static string Index_Card_About_Body {
            get {
                return ResourceManager.GetString("Index_Card_About_Body", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        public static string Index_Card_About_Title {
            get {
                return ResourceManager.GetString("Index_Card_About_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Play the game.
        /// </summary>
        public static string Index_Card_Game_Action {
            get {
                return ResourceManager.GetString("Index_Card_Game_Action", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Play the game and try to crack the code..
        /// </summary>
        public static string Index_Card_Game_Body {
            get {
                return ResourceManager.GetString("Index_Card_Game_Body", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Game.
        /// </summary>
        public static string Index_Card_Game_Title {
            get {
                return ResourceManager.GetString("Index_Card_Game_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show the reports.
        /// </summary>
        public static string Index_Card_Reports_Action {
            get {
                return ResourceManager.GetString("Index_Card_Reports_Action", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Here you can view played games..
        /// </summary>
        public static string Index_Card_Reports_Body {
            get {
                return ResourceManager.GetString("Index_Card_Reports_Body", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reports.
        /// </summary>
        public static string Index_Card_Reports_Title {
            get {
                return ResourceManager.GetString("Index_Card_Reports_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome to.
        /// </summary>
        public static string Index_Welcome {
            get {
                return ResourceManager.GetString("Index_Welcome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to English.
        /// </summary>
        public static string Language_English {
            get {
                return ResourceManager.GetString("Language_English", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to German.
        /// </summary>
        public static string Language_German {
            get {
                return ResourceManager.GetString("Language_German", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select language:.
        /// </summary>
        public static string Language_Select_Label {
            get {
                return ResourceManager.GetString("Language_Select_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Waiting for games... ⌛.
        /// </summary>
        public static string LivePage_WaitingForGames {
            get {
                return ResourceManager.GetString("LivePage_WaitingForGames", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        public static string NavMenu_About_Title {
            get {
                return ResourceManager.GetString("NavMenu_About_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Game.
        /// </summary>
        public static string NavMenu_Game_Title {
            get {
                return ResourceManager.GetString("NavMenu_Game_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        public static string NavMenu_Home_Title {
            get {
                return ResourceManager.GetString("NavMenu_Home_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reports.
        /// </summary>
        public static string NavMenu_Reports_Title {
            get {
                return ResourceManager.GetString("NavMenu_Reports_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        public static string No {
            get {
                return ResourceManager.GetString("No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Move.
        /// </summary>
        public static string PegSelection_MakeMove {
            get {
                return ResourceManager.GetString("PegSelection_MakeMove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No reports found.
        /// </summary>
        public static string Report_NoReports {
            get {
                return ResourceManager.GetString("Report_NoReports", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select the date.
        /// </summary>
        public static string Report_SelectDate_Label {
            get {
                return ResourceManager.GetString("Report_SelectDate_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Load games.
        /// </summary>
        public static string Reports_LoadGames_Action {
            get {
                return ResourceManager.GetString("Reports_LoadGames_Action", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gamername,Start,End,Number of Moves.
        /// </summary>
        public static string Reports_Table_Headers {
            get {
                return ResourceManager.GetString("Reports_Table_Headers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reports.
        /// </summary>
        public static string Reports_Title {
            get {
                return ResourceManager.GetString("Reports_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About this application.
        /// </summary>
        public static string Settings_About {
            get {
                return ResourceManager.GetString("Settings_About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TODO: Replace with your app description..
        /// </summary>
        public static string Settings_AboutDescription {
            get {
                return ResourceManager.GetString("Settings_AboutDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language.
        /// </summary>
        public static string Settings_Language {
            get {
                return ResourceManager.GetString("Settings_Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Default.
        /// </summary>
        public static string Settings_Language_Default {
            get {
                return ResourceManager.GetString("Settings_Language_Default", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to English.
        /// </summary>
        public static string Settings_Language_English {
            get {
                return ResourceManager.GetString("Settings_Language_English", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to German.
        /// </summary>
        public static string Settings_Language_German {
            get {
                return ResourceManager.GetString("Settings_Language_German", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Personalization.
        /// </summary>
        public static string Settings_Personalization {
            get {
                return ResourceManager.GetString("Settings_Personalization", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Theme.
        /// </summary>
        public static string Settings_Theme {
            get {
                return ResourceManager.GetString("Settings_Theme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dark.
        /// </summary>
        public static string Settings_Theme_Dark {
            get {
                return ResourceManager.GetString("Settings_Theme_Dark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Default.
        /// </summary>
        public static string Settings_Theme_Default {
            get {
                return ResourceManager.GetString("Settings_Theme_Default", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Light.
        /// </summary>
        public static string Settings_Theme_Light {
            get {
                return ResourceManager.GetString("Settings_Theme_Light", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The language will change after the next start of the application..
        /// </summary>
        public static string SettingsPage_LanguageChangeInfoMessage {
            get {
                return ResourceManager.GetString("SettingsPage_LanguageChangeInfoMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Privacy Statement.
        /// </summary>
        public static string SettingsPage_PrivacyTermsLink {
            get {
                return ResourceManager.GetString("SettingsPage_PrivacyTermsLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://YourPrivacyUrlGoesHere/.
        /// </summary>
        public static string SettingsPage_PrivacyTermsLinkNavigateUri {
            get {
                return ResourceManager.GetString("SettingsPage_PrivacyTermsLinkNavigateUri", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Blank.
        /// </summary>
        public static string ShellPage_Blank {
            get {
                return ResourceManager.GetString("ShellPage_Blank", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Game.
        /// </summary>
        public static string ShellPage_GameTab {
            get {
                return ResourceManager.GetString("ShellPage_GameTab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Live.
        /// </summary>
        public static string ShellPage_LiveTab {
            get {
                return ResourceManager.GetString("ShellPage_LiveTab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        public static string Yes {
            get {
                return ResourceManager.GetString("Yes", resourceCulture);
            }
        }
    }
}
