@Codebreaker.Bot_HostAddress = https://localhost:5142
@ContentType = application/json

### Start default games to play
# @name start1
POST {{Codebreaker.Bot_HostAddress}}/bot/bots

### Get information on the first games playing

GET {{Codebreaker.Bot_HostAddress}}/bot/bots/{{start1.response.body.$.*}}

### Start 30 games with different parameter settings
# @name start2
POST {{Codebreaker.Bot_HostAddress}}/bot/bots?count=30&delay=2&thinkTime=1

### Get information on the second games playing

GET {{Codebreaker.Bot_HostAddress}}/bot/bots/{{start2.response.body.$.*}}
